buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        jcenter()
    }
    dependencies {
        classpath 'ru.vyarus:gradle-quality-plugin:4.4.0'
    }
}

ext {
    spigotVersion = '1.11-R0.1-SNAPSHOT'
    bungeeVersion = '1.21-R0.4-SNAPSHOT'
    velocityVersion = '3.4.0-SNAPSHOT'
    adventureVersion = '4.18.0'
    spongeVersion = '7.0.0'
    dataApiVersion = '1.0.2-SNAPSHOT'
    viaVersion = '4.0.0'
    geyserApiVersion = '2.9.0-SNAPSHOT'
    floodgateApiVersion = '2.2.4-SNAPSHOT'
}

allprojects {
    group = 'codecrafter47.bungeetablistplus'
    version = '3.6.8-SNAPSHOT'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'ru.vyarus.quality'

    repositories {
        mavenCentral()

        maven {
            name = 'ViaVersion'
            url = uri('https://repo.viaversion.com/everything/')
            content {
                includeGroupByRegex "com\\.viaversion(\\..*)?"
            }
        }

        maven {
            name = 'GeyserMC'
            url = uri('https://repo.opencollab.dev/main/')
            content {
                includeGroupByRegex "org\\.geysermc(\\..*)?"
                includeGroupByRegex "org\\.cloudburstmc(\\..*)?"
            }
        }

        maven {
            name = 'GeyserMC Snapshots'
            url = uri('https://repo.opencollab.dev/maven-snapshots/')
            content {
                includeGroupByRegex "org\\.geysermc(\\..*)?"
                includeGroupByRegex "org\\.cloudburstmc(\\..*)?"
            }
        }

        maven {
            name = 'CloudburstMC'
            url = uri('https://repo.cloudburstmc.org/repository/maven-public/')
            content {
                includeGroupByRegex "org\\.cloudburstmc(\\..*)?"
            }
        }

        maven {
            name = 'LoohpJames'
            url = uri('https://repo.loohpjames.com/repository/')
            content {
                includeGroup 'org.cloudburstmc.math'
            }
        }

        maven {
            name = 'CodeCrafter47'
            url = uri('https://nexus.codecrafter47.de/content/repositories/public/')
        }

        maven {
            name = 'CodeMC'
            url = uri('https://repo.codemc.io/repository/maven-public/')
        }

        maven {
            name = 'BungeeCord Snapshots'
            url = uri('https://repo.md-5.net/content/repositories/snapshots/')
        }

        maven {
            name = 'Spigot Snapshots'
            url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/')
        }

        maven {
            name = 'PaperMC'
            url = uri('https://repo.papermc.io/repository/maven-public/')
        }

        maven {
            name = 'Sponge'
            url = uri('https://repo.spongepowered.org/maven')
        }

        maven {
            name = 'JitPack'
            url = uri('https://jitpack.io')
        }

        maven {
            name = 'Sonatype Snapshots'
            url = uri('https://oss.sonatype.org/content/repositories/snapshots')
        }

        maven {
            name = 'PRGM'
            url = uri('https://nexus.prgm.in/repository/maven-public/')
            content {
                includeGroup 'com.imaginarycode.minecraft'
                includeGroup 'protocolsupport'
            }
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.34'
        annotationProcessor 'org.projectlombok:lombok:1.18.34'
        testCompileOnly 'org.projectlombok:lombok:1.18.34'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
        compileOnly 'com.google.code.findbugs:jsr305:3.0.1'
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(8))
        }
    }

    publishing {
        repositories {
            maven {
                if (project.version.endsWith("-SNAPSHOT")) {
                    url "https://nexus.codecrafter47.de/content/repositories/snapshots/"
                } else {
                    url "https://nexus.codecrafter47.de/content/repositories/releases/"
                }
                credentials {
                    username "${project.properties.mavenUser}"
                    password "${project.properties.mavenPassword}"
                }
            }
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    quality {
        strict = false
    }

    tasks.withType(Javadoc) {
        failOnError false
    }
}
